[package]
name = "adventures-in-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
piston = "0.55.0"
piston2d-graphics = "0.44.0"
piston2d-opengl_graphics = "0.83.0"
pistoncore-glutin_window = "0.72.0"